version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  api_gateway:
    build: ./api_gateway
    ports:
      - "3001:3000"
    links:
      - "db_localization:database"
      - "mservice_fi:mservice_fi"
  mservice_fi:
    build: ./mservice_fi
    links:
      - "db_fi:database"
      - "mservice_fi:mservice_fi"
    ports:
    - "8888:8888"
  mservice_fca:
    build: ./mservice_fca
    ports:
      - "3003:8888"
    links:
      - "db_fca:database"
  mservice_fcsh:
    build: ./mservice_fcsh
    ports:
      - "3004:8888"
    links:
      - "db_fcsh:database"
  db_fi:
    image: "postgres:latest"
    restart: always
    environment:
      POSTGRES_USER: uaslp_fi
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: uaslp_fi
    volumes:
       - ./data_fi:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  db_fca:
    image: "postgres:latest"
    restart: always
    environment:
      POSTGRES_USER: uaslp_fca
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: uaslp_fca
    volumes:
       - ./data_fca:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  db_fcsh:
    image: "postgres:latest"
    restart: always
    environment:
      POSTGRES_USER: uaslp_fcsh
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: uaslp_fcsh
    volumes:
       - ./data_fcsh:/var/lib/postgresql/data
    ports:
      - "5434:5432"
  db_localization:
    image: "postgres:latest"
    restart: always
    environment:
      POSTGRES_USER: uaslp_localization
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: uaslp_localization
    volumes:
       - ./data_localization:/var/lib/postgresql/data
    ports:
      - "5435:5432"